services:
  raspotify:
    image: cyb3rdoc/raspotify:latest
    container_name: raspotify
    hostname: raspotify
    network_mode: host
    environment:
      - TZ=UTC
    devices:
      - /dev/snd:/dev/snd
    restart: unless-stopped
